os: linux
dist: bionic
language: shell
branches:
  only:
    - master
before_install:
  - set -e
  # Configure environment so changes are picked up when the Docker daemon is restarted after upgrading
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  # Upgrade to Docker CE 19.03 for BuildKit support
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce=5:19.03.8~3-0~ubuntu-bionic # pin version for reproducibility
  - sudo apt-get install -y uidmap dos2unix
  # Show info to simplify debugging and create a builder
  - docker info
  - docker buildx create --name builder --use
  - docker buildx ls
  # Prepare openHAB container build
  - ./update-docker-files.sh
  - source ./update-functions.sh
  - validate_readme_constraints
  - sudo apt-get install -y uidmap dos2unix
  - docker info
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - ARCHES="amd64 armhf arm64"
  - dos2unix template/*.sh
install:
  - mkdir $VERSION
  - cp template/manifest.yml $VERSION/
  - sed -i -e "s|%version%|$VERSION|" -e "s|%tags%|$TAGS|" $VERSION/manifest.yml
  - echo "-------- Manifest $VERSION --------";
  - cat $VERSION/manifest.yml
  - mkdir $VERSION/cont-init.d
  - cp template/00-jython_initialize.sh $VERSION/cont-init.d/
  - for ARCH in $ARCHES; do
        cp template/Dockerfile $VERSION/Dockerfile.$ARCH;
        sed -i -e "s|%version%|$VERSION|" -e "s|%arch%|$ARCH|" $VERSION/Dockerfile.$ARCH;
        sed -i -e "s|%signal_version%|$SIGNAL_VERSION|" $VERSION/Dockerfile.$ARCH;
        echo "-------- Dockerfile $VERSION $ARCH --------";
        cat $VERSION/Dockerfile.$ARCH;
        docker build --build-arg VCS_REF=$TRAVIS_COMMIT --build-arg BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ") --build-arg VERSION=$VERSION -f $VERSION/Dockerfile.$ARCH -t $DOCKER_REPO:$VERSION-$ARCH $VERSION;
    done
after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        export MT_SHA256="80906341c3306e3838437eeb08fff5da2c38bd89149019aa301c7745e07ea8f9"
        sudo curl -fSL "https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64" -o "/usr/local/bin/manifest-tool"
        echo "${MT_SHA256}  /usr/local/bin/manifest-tool" | sha256sum -c -
        sudo chmod a+x "/usr/local/bin/manifest-tool"
        echo "manifest-tool installed!"
        docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
        for ARCH in $ARCHES; do
            docker push $DOCKER_REPO:$VERSION-$ARCH;
        done
        manifest-tool push from-spec $VERSION/manifest.yml
    fi
matrix:
  fast_finish: true
env:
  global:
    - SIGNAL_VERSION=0.6.7
  matrix:
    - VERSION=2.5.5 TAGS=latest
    - VERSION=2.5.6-snapshot TAGS=2.5.X-snapshot
    - VERSION=3.0.0-snapshot TAGS=3.0.0-snapshot,snapshot
